### ISSUE TITLE
Taas Admin app: feature

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#1]
Description:

Taas Admin app api challenge: https://www.topcoder.com/challenges/acb9d8ea-6960-4016-a844-9970bc9c58f5
TaaS Admin App - Basic Work Periods: https://www.topcoder.com/challenges/256744b5-db4f-471d-807b-51c681486ca8
Design: https://marvelapp.com/prototype/g6g2jh7/screen/78212448

**Comment by maxceem** [comment]
This is ready for QA on DEV.

Know issues:
- filtering by Payment Status is hidden, because API doesn't support filtering by multiple paymentStatus yet. Instead of it we added filtering by user handle, so we can test filtering in general
- sorting by Working Days doesn't work correctly for now, I'm thinking about solutions

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

https://docs.google.com/spreadsheets/d/1-hLN9isB0aL0kOPTEzQDPpdh8pfZDNqm4iw9FAt29og/edit#gid=1421947240

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
