### ISSUE TITLE
[$30] Nice to have: Failure message with the reason for failure.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#48]
Description:

Currently if there was a failure in scheduling the payment, we are getting the error message "Failed to schedule payments for (n) resources" for all below reason,
1. If member Rate is 0 or null
2. If the RB.billingaccount is null.
3. If status='no days'

It will be nice if there is a reason added for the failure as it would be easier to find the reason

![image](https://user-images.githubusercontent.com/55895538/123258461-5b2fc000-d52e-11eb-8b29-35f0271f0ad0.png)

**Comment by maxceem** [comment]
Sum up:
- I suggest another approach, instead of showing error after attempt of processing the payment we should disable the checkboxes if we cannot process the payment for a known reason.
  - disable checkboxes for the rows for which we cannot process a payment because of one of the reasons shown below
  - when we put mouse on a disabled checkbox show the Tooltip with the message describing the reason why we cannot process the payment for this row
  - if we click checkbox to select `all` it should not select disabled checkboxes.

Possible Reasons:
- `RB.mamberRate` is `0` or `null`, message: `Member Rate should be more than 0`.
- `RB.billingAccount` is `null`, message: `Billing Account is not set for the Resorce Booking`.
- if `RB.workPeriods[0].daysWorked - RB.workPeriods[0].daysPaid === 0`, message: `There are no days to pay`.

**Comment by maxceem** [comment]
@MadOPcode all good now, nothing has been changed.

**Comment by sandhiyakavi** [comment]
@maxceem 1. The 'Resource' spelling is incorrect in the tooltip.

![image](https://user-images.githubusercontent.com/55895538/124446863-c6de1c80-ddbb-11eb-8880-f15021f1e5c7.png)

2. Also can we have a bulletin point or similar one to display these messages if they are more than one?

![image](https://user-images.githubusercontent.com/55895538/124447015-f2610700-ddbb-11eb-945e-090e27844c7c.png)

Other than the above two, it is working fine

**Comment by maxceem** [comment]
@sandhiyakavi both are fixed now and pushed to DEV.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/124456636-e7ab6f80-ddc5-11eb-8b14-6a7811fb151a.png)

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/ed92a075-8557-47ac-9a86-d0955ea472bf

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
