### ISSUE TITLE
[$50] Nice to have: userhandle near WP id for the Warning messages displayed during multiple payment process

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#54]
Description:

Currently for mentioning the error only WP id of the Resource is mentioned in the warning messages of multiple payment process. It would be nice to have Userhandle near the WP id for easy identifying of the particular resource.

Steps to Reproduce:
1. Make the member rate zero for a resouce.
2. Remove the BA of another resource.
3. Make daysworked as 0 for another resouce.
4. Choose a payment completed resource.
5. Process payment for above resources.

![error_check](https://user-images.githubusercontent.com/55895538/123624686-d3a5c200-d849-11eb-8d22-1675e42bd69d.png)

**Comment by maxceem** [comment]
Sum up:

I suggested instead of adding user handles to the error messages, move the errors messages to the rows.
- When error of payment processing happens to some row, we already make such rows red color now.
- Additionally to that, add a red circle with `!` inside on the right to the checkbox like this: 

   ![image](https://user-images.githubusercontent.com/146016/123959545-facdd200-d9b6-11eb-8254-0eee467d67ef.png)
   
   - when we click on it, show a popover with error message from the server
- Remove the list of error messages from the toastr. Only show how many payment were successfully scheduled and how many failed, but without the list of error messages.

**Comment by sandhiyakavi** [comment]
@maxceem Currently only for select all records, Failed to schedule payment is displayed but for that too, 'red circle with !  on the right to the checkbox' is not shown

<img width="959" alt="failed" src="https://user-images.githubusercontent.com/55895538/124550142-32cb8e00-de6b-11eb-8a57-2e53d1fa720c.png">

https://user-images.githubusercontent.com/55895538/124550165-39f29c00-de6b-11eb-84bb-bf306de5bfd5.mp4

**Comment by maxceem** [comment]
@sandhiyakavi Got your point. This feature to pay ALL the payments were implemented to support a big number of payments. So we implemented API to NOT return actually errors that happened, only the number of success and failed payments. That's why at the moment we cannot show details of errors.

Though we can give it a try and implement it. I suggest logging a separate issue for this case where we could discuss the details, as there are some questions raise up.

**Comment by sandhiyakavi** [comment]
@maxceem I think there is no way to test this with either single or multiple payments after the implementation of this https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/48 right?

**Comment by maxceem** [comment]
Ah, yes, @sandhiyakavi when I tested it locally, I disabled #48 so I can see the error details messages.

**Comment by sandhiyakavi** [comment]
@maxceem I marked this as pass, as this issue will be resolved with #48

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/85a45330-c43a-41ac-bf1f-e0667ba181b1

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
