### ISSUE TITLE
Green tick displayed for Working Days which is not actually changed.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-taas-admin-app#63]
Description:

Refer https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/50#issuecomment-873955109:

> Currently if we try to increase WorkingDays beyond its fitting to the RB dates,error message is getting displayed but if we try to again change it back to its previous number(without refreshing), the green tick mark is getting displayed which should not happen as the number is not changed in this case.

> https://user-images.githubusercontent.com/55895538/124448821-cd6d9380-ddbd-11eb-917c-562ea955b25c.mp4

**Comment by maxceem** [comment]
I suggest the next solution:
- if error during API request happens, we have to revert to the previous value, so this case as shown in the video would work like this:
   - current value is `0`
   - we increase value to `1`
   - error happens during server request
   - we revert the value to the previous one `0`
- the tricky moment how to handle a case, where we click increase/decrease several times and some requests failed and some of the are success, can we make a nice logic in such a case

**Comment by maxceem** [comment]
We implemented it another way via https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/37.
So we don't allow to increase/decrease the value if that value is not suitable and this error would never happen now.

It may still happen that some other error would happen on the server, but the chance is very small, so I suggest leave such rare edge cases as it is, because fixing this issue for such edge cases could be quite complex in comparison with issue severity. If we get feedback from admins that they come to this issue again we could consider fixing it.

What do you think @sandhiyakavi?

**Comment by sandhiyakavi** [comment]
@maxceem Yes, with #37 fix this issue won't happen

**Comment by maxceem** [comment]
@sandhiyakavi as https://github.com/topcoder-platform/micro-frontends-taas-admin-app/issues/37 is implemented now, I guess we may consider this issue as resolved, as this would rarely happen now.

**Comment by sandhiyakavi** [comment]
Issue resolved with #37
